repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
      exclude: ^tools/
    - id: golangci-lint
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: build-docs
      name: Build Docs
      entry: go run ./docs/docs.go
      language: system
      pass_filenames: false
